#!/bin/bash

cd /Users/owner/Documents/Programming/projects/quant_fund/spark

kubectl create -f setup

for i in {1..150}
do
    echo "Checking if zeppelin pod is running..."
    if kubectl get pods --field-selector=status.phase=Running --output=name | grep zeppelin; then
        break
    fi
    sleep 3
done

export POD=`kubectl get pods --output=name --no-headers | sed "s/^.\{4\}//" | grep zeppelin`

kubectl port-forward $POD 8080:8080
